<?php

class Dog extends Pet
{
    //
    function fetch()
    {
        echo "<p>" . $this->getName() . " is fetching. </p>";
    }

    function talk()
    {
        echo $this->getName() . " is barking<br>";
        /*parent::talk(); // TODO: Change the autogenerated stub*/
    }
}// end of dog class
